git:
  remote:
    upstream: 'mongodb/docs-yourrepo'
    tools: 'mongodb/docs-tools'
project:
  name: 'mongodb-runbooks'
  tag: 'mongodb-runbooks'
  url: 'https://docs.mongodb.com/runbooks'
  title: 'MongoDB Meta Documentation'
  branched: false
system:
  files:
    - 'sphinx_local.yaml'
    - 'integration.yaml'
    - 'intersphinx.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
paths:
  output: 'build-runbooks'
  source: 'source'
  includes: 'source/includes'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...
